## 读取电影评价数据

In [1]:
import pandas as pd

In [2]:
df_rating = pd.read_csv("../dataset/processed_users_ratings_statistics.csv")
df_rating_head = df_rating.head(1000)
df_rating_head.head()

,Rating,UserId,MovieId,Timestamp,rmax,rmin,rcount,rsum,ravg,rmedian
0,2.0,1,657,2018-01-05 15:05:06,10.0,2.0,5,42.0,8.4,10.0
1,10.0,1,2879,2018-01-25 13:58:16,10.0,2.0,5,42.0,8.4,10.0
2,10.0,1,15257,2018-01-28 13:48:20,10.0,2.0,5,42.0,8.4,10.0
3,10.0,1,21808,2018-01-28 14:07:27,10.0,2.0,5,42.0,8.4,10.0
4,10.0,1,14807,2018-01-28 14:25:42,10.0,2.0,5,42.0,8.4,10.0

In [3]:
df_rating.shape

(199813, 10)

In [4]:
df_movie = pd.read_csv("../dataset/processed_movies.csv")
df_movie_head = df_movie.head(1000)
df_movie_head.head()

,actors,director,name,rat,region,traits,type,movie_id
0,杰夫里·乔 Jeffrey Chyau|姜星 Sung Kang|吴玉 Jade Wu|萨曼...,迈克·姜 Michael Kang,汽车旅馆,7.0,美国,青春|文艺,喜剧|剧情,1
1,海瑟·格拉汉姆|杰瑞·奥康奈尔|约翰·考伯特,Brian Herzlinger,安吉拉怀孕记,5.7,美国,女性,爱情|喜剧,2
2,史蒂夫·卡瑞尔|摩根·弗里曼|劳伦·格拉汉姆|约翰尼·西蒙斯|约翰·古德曼,汤姆·沙迪亚克,冒牌天神2,6.5,美国,魔幻|励志|搞笑,科幻|喜剧|奇幻|剧情,3
3,安吉拉·兰斯伯瑞|杰拉丁·卓别林|托尼·柯蒂斯|爱德华·福克斯|罗克·赫德森,盖伊·汉弥尔顿,破镜谋杀案,7.0,英国,经典,悬疑|惊悚|犯罪,4
4,北野武|浅野忠信|大楠道代|夏川结衣|岸部一德,北野武,座头市,8.0,日本,经典,音乐|犯罪|动作|剧情|武侠,5

In [5]:
df_movie.shape

(23034, 8)

In [6]:
df_data_head = pd.merge(df_rating_head, df_movie_head, left_on=['MovieId'], right_on=['movie_id'])
df_data_head.head()

,Rating,UserId,MovieId,Timestamp,rmax,rmin,rcount,rsum,ravg,rmedian,actors,director,name,rat,region,traits,type,movie_id
0,2.0,1,657,2018-01-05 15:05:06,10.0,2.0,5,42.0,8.400000,10.0,姬晨牧,喻瀚湫,心雨花露,6.4,中国大陆,青春|励志,爱情,657
1,8.0,3,940,2018-01-05 15:19:21,10.0,2.0,138,970.0,7.028986,8.0,刘萌萌|李宁|康恩赫|张炜迅|罗光敏,李长欣,时光大战,3.2,中国大陆,青春,科幻|动作,940
2,10.0,3,112,2018-01-08 15:08:28,10.0,2.0,138,970.0,7.028986,8.0,Don Francks|Peter Keleghan|Lindy Booth|Jackie ...,Fred Gerber,音乐先生,7.7,加拿大,青春,喜剧|音乐,112
3,4.0,3,52,2018-01-19 15:59:30,10.0,2.0,138,970.0,7.028986,8.0,托尼·塞尔维洛|Francesco Di Leva|茱莉安·柯勒|Leonardo Spre...,克劳迪奥·库佩利尼,宁静的人生,6.2,意大利,黑帮,爱情|动作|犯罪|剧情,52
4,8.0,3,627,2018-01-19 16:07:02,10.0,2.0,138,970.0,7.028986,8.0,森田亚纪|栗林里莉|川上奈奈美|伊东红|住吉真理子,森川圭,A片现场不NG,5.9,日本,女性,情色|喜剧|剧情,627

In [7]:
df_data = pd.merge(df_rating, df_movie, left_on=['MovieId'], right_on=['movie_id'])
df_data.shape

(199813, 18)

In [8]:
df_data.head().T

,0,1,2,3,4
Rating,2,8,8,10,10
UserId,1,613,4919,7679,7884
MovieId,657,657,657,657,657
Timestamp,2018-01-05 15:05:06,2018-01-24 16:06:00,2018-01-18 13:30:05,2018-01-22 13:23:35,2018-01-08 12:24:36
rmax,10,10,10,10,10
rmin,2,2,4,4,4
rcount,5,57,27,75,94
rsum,42,456,232,612,810
ravg,8.4,8,8.59259,8.16,8.61702
rmedian,10,8,8,8,8
actors,姬晨牧,姬晨牧,姬晨牧,姬晨牧,姬晨牧
director,喻瀚湫,喻瀚湫,喻瀚湫,喻瀚湫,喻瀚湫
name,心雨花露,心雨花露,心雨花露,心雨花露,心雨花露
rat,6.4,6.4,6.4,6.4,6.4
region,中国大陆,中国大陆,中国大陆,中国大陆,中国大陆
traits,青春|励志,青春|励志,青春|励志,青春|励志,青春|励志
type,爱情,爱情,爱情,爱情,爱情
movie_id,657,657,657,657,657

In [9]:
df_data.to_csv("../dataset/comment_origin_data_1.csv")

In [10]:
df_data.iloc[1000]

Rating                                         4
UserId                                      6846
MovieId                                     9858
Timestamp                    2018-01-23 21:18:59
rmax                                          10
rmin                                           2
rcount                                        16
rsum                                          90
ravg                                       5.625
rmedian                                        4
actors       阿尔·帕西诺|卡梅隆·迪亚兹|丹尼斯·奎德|詹姆斯·伍兹|杰米·福克斯
director                                  奥利佛·斯通
name                                       挑战星期天
rat                                          7.9
region                                        美国
traits                                        励志
type                                          剧情
movie_id                                    9858
Name: 1000, dtype: object